/* ==========================================================================
   Q2NSViz documentation site customizations
   --------------------------------------------------------------------------
   Responsibilities:
   1. Inject sidebar logo
   2. Move the Doxygen search box into the sidebar
   3. Make badge links open in a new tab
   4. Add sidebar credit
   ========================================================================== */

document.addEventListener("DOMContentLoaded", function () {
  const sideNav = document.getElementById("side-nav");

  injectSidebarLogo(sideNav);
  moveSearchIntoSidebar(sideNav);
  externalizeBadgeLinks();
  addSidebarCredit(sideNav);
});

/* ==========================================================================
   1. Sidebar logo
   ========================================================================== */

function injectSidebarLogo(sideNav) {
  if (!sideNav || document.getElementById("q2nsviz-sidebar-logo")) {
    return;
  }

  const logo = document.createElement("div");
  logo.id = "q2nsviz-sidebar-logo";
  logo.innerHTML = `
    <div class="q2nsviz-sidebar-logo-card" aria-label="QNattyNet">
      <img src="logo-qnattynet.png" alt="QNattyNet">
    </div>
  `;

  sideNav.prepend(logo);
}

/* ==========================================================================
   2. Sidebar search
   ========================================================================== */

function moveSearchIntoSidebar(sideNav) {
  if (!sideNav || document.getElementById("q2nsviz-sidebar-search")) {
    return;
  }

  const logo = document.getElementById("q2nsviz-sidebar-logo");
  if (!logo) {
    return;
  }

  const tryMoveSearch = () => {
    const searchBox =
      document.getElementById("MSearchBox") ||
      document.getElementById("searchBox") ||
      document.querySelector(".searchBox") ||
      document.querySelector(".search") ||
      document.querySelector("#FSearchBox") ||
      document.querySelector(".MSearchBox");

    if (!searchBox) {
      return false;
    }

    const wrapper = document.createElement("div");
    wrapper.id = "q2nsviz-sidebar-search";
    wrapper.appendChild(searchBox);

    logo.insertAdjacentElement("afterend", wrapper);
    return true;
  };

  if (tryMoveSearch()) {
    return;
  }

  window.addEventListener("load", function () {
    if (document.getElementById("q2nsviz-sidebar-search")) {
      return;
    }

    if (tryMoveSearch()) {
      return;
    }

    let attempts = 0;
    const maxAttempts = 20;
    const interval = setInterval(() => {
      attempts += 1;
      if (
        document.getElementById("q2nsviz-sidebar-search") ||
        tryMoveSearch() ||
        attempts >= maxAttempts
      ) {
        clearInterval(interval);
      }
    }, 200);
  });
}

/* ==========================================================================
   3. External behavior for main-page badges only
   ========================================================================== */

function externalizeBadgeLinks() {
  document.querySelectorAll(".q2nsviz-badges a").forEach((a) => {
    a.setAttribute("target", "_blank");
    a.setAttribute("rel", "noopener noreferrer");
  });
}

/* ==========================================================================
   4. Sidebar credit
   ========================================================================== */

function addSidebarCredit(sideNav) {
  if (!sideNav || document.getElementById("q2nsviz-sidebar-credit")) {
    return;
  }

  const credit = document.createElement("div");
  credit.id = "q2nsviz-sidebar-credit";
  credit.innerHTML = `
    Generated by
    <a href="https://www.doxygen.nl/" target="_blank" rel="noopener noreferrer">Doxygen</a>
    ·
    <a href="https://jothepro.github.io/doxygen-awesome-css/" target="_blank" rel="noopener noreferrer">Doxygen Awesome</a>
  `;

  sideNav.appendChild(credit);
}
